In [8]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\nasri\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\nasri\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nasri\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [9]:
import pandas as pd
import numpy as np

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

In [10]:
df = pd.read_csv("data/news.csv")
df.head()

,title,content
0,Google launches AI startup program,Google announced a new AI startup program in I...
1,Elections coming soon in India,The election commission announced upcoming ele...

In [11]:
stop_words = set(stopwords.words('english'))

def clean_text(text):
    tokens = word_tokenize(text.lower())
    tokens = [word for word in tokens if word.isalpha()]
    tokens = [word for word in tokens if word not in stop_words]
    return " ".join(tokens)

df['clean_text'] = df['content'].astype(str).apply(clean_text)
df.head()

,title,content,clean_text
0,Google launches AI startup program,Google announced a new AI startup program in I...,google announced new ai startup program india
1,Elections coming soon in India,The election commission announced upcoming ele...,election commission announced upcoming elections

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(min_df=1, max_df=2) 

X = tfidf.fit_transform(df['clean_text'])

print(X.shape)

(2, 11)

In [21]:
from sklearn.cluster import KMeans

num_clusters = 2

kmeans = KMeans(n_clusters=num_clusters, random_state=42)
kmeans.fit(X)

df['cluster'] = kmeans.labels_


print("\nDocument clusters:")
print(df[['title','cluster']])

Document clusters:
                                title  cluster
0  Google launches AI startup program        0
1      Elections coming soon in India        1

In [22]:

terms = tfidf.get_feature_names_out()

order_centroids = kmeans.cluster_centers_.argsort()[:, ::-1]

print("\nTop keywords per cluster:")
for i in range(num_clusters):
    print(f"\nCluster {i}:")
    for ind in order_centroids[i, :5]:  
        print(f" {terms[ind]}")

Top keywords per cluster:

Cluster 0:
 startup
 program
 new
 google
 india

Cluster 1:
 upcoming
 election
 elections
 commission
 announced